"""Design tokens compartidos para mantener consistencia visual en la app."""

# Spacing scale
SPACE_8 = 8
SPACE_12 = 12
SPACE_16 = 16
SPACE_20 = 20
SPACE_24 = 24

# Corner radii
RADIUS_SM = 10
RADIUS_MD = 10
RADIUS_LG = 10

# Control sizing
CONTROL_HEIGHT = 40
CONTROL_HEIGHT_COMPACT = 36
CONTROL_HEIGHT_LARGE = 44

# Surfaces and borders
COLOR_BG_APP = "#F3F4F6"
COLOR_BG_SUBTLE = "#F8FAFC"
COLOR_SURFACE = "#FFFFFF"
COLOR_SURFACE_ALT = "#FCFDFE"
COLOR_BORDER = "#DDE3EA"
COLOR_BORDER_STRONG = "#CBD5E1"

# Typography
COLOR_TEXT_PRIMARY = "#111827"
COLOR_TEXT_SECONDARY = "#6B7280"

# Brand / state colors
COLOR_PRIMARY = "#2563EB"
COLOR_PRIMARY_HOVER = "#1D4ED8"
COLOR_PRIMARY_PRESSED = "#1E40AF"
COLOR_SUCCESS = "#10B981"
COLOR_SUCCESS_HOVER = "#059669"
COLOR_SUCCESS_PRESSED = "#047857"
COLOR_SUCCESS_SOFT_BG = "#ECFDF5"
COLOR_SUCCESS_SOFT_BORDER = "#BBF7D0"
COLOR_SUCCESS_SOFT_TEXT = "#166534"
COLOR_DANGER = "#EF4444"
