# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main_client.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/images/logo.png', 'assets/images'),
        ('icon.ico', '.'),
    ],
    hiddenimports=[
        # reportlab uses dynamic imports internally — PyInstaller misses these
        'reportlab.graphics',
        'reportlab.graphics.barcode',
        'reportlab.graphics.barcode.code128',
        'reportlab.graphics.barcode.code39',
        'reportlab.graphics.barcode.code93',
        'reportlab.graphics.barcode.common',
        'reportlab.graphics.barcode.qr',
        'reportlab.graphics.barcode.qrencoder',
        'reportlab.graphics.barcode.widgets',
        'reportlab.graphics.renderPDF',
        'reportlab.graphics.renderPM',
        'reportlab.graphics.renderbase',
        'reportlab.graphics.shapes',
        'reportlab.graphics.transform',
        'reportlab.graphics.utils',
        'reportlab.graphics.widgetbase',
        'reportlab.lib',
        'reportlab.lib.colors',
        'reportlab.lib.enums',
        'reportlab.lib.fonts',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.lib.utils',
        'reportlab.lib.validators',
        'reportlab.pdfbase',
        'reportlab.pdfbase._fontdata',
        'reportlab.pdfbase.pdfdoc',
        'reportlab.pdfbase.pdfmetrics',
        'reportlab.pdfbase.ttfonts',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.platypus',
        'reportlab.platypus.doctemplate',
        'reportlab.platypus.flowables',
        'reportlab.platypus.frames',
        'reportlab.platypus.paragraph',
        'reportlab.platypus.tables',
        'reportlab.rl_config',
        'reportlab.rl_settings',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main_client',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
